#! /bin/bash
installPath="INSTALLPATH"
testDir=$installPath/test_src
tempDir=$installPath/temp
logDir=$installPath/log
interval=5m #INTERVAL
ftpRoot="FTPROOT"
ftpTemp=$ftpRoot/temp
userName="USERNAME"
timeOut="10" #Time Unit: second
SID=$RANDOM

checkRun(){
	$*
	errCode=$?
	if [ $errCode != 0 ]
	then 
		echo "[`date`][SID] Error occurred while executing command line: \"$*\". Returned with error code ($errCode)"
		exit
	fi
}

timeTransform(){
	arg=$1
	wordCount=${#arg}
	postfix=${arg:$[wordCount - 1]:1}
	arg=`echo $arg | sed "s/$postfix//g"`
	case $postfix in
	m) echo "-mmin -$arg";;
	h) echo "-mmin -$[arg * 60]";;
	d) echo "-mtime -$arg";;
	*) exit;;
	esac
}

intervalArg=`timeTransform $interval`

checkLab(){
	tiggerDir=$ftpRoot/$stuID/tigger
	empty=`checkRun ls $tiggerDir`
	changeFlag=`checkRun find $tiggerDir $intervalArg`
	#echo "find $tiggerDir $intervalArg"
	if [ "${changeFlag}x" != x -a "${empty}x" != x ]
	then 
		# Start compiling
		echo -e "  Check report for lab \"tigger\":\n" > $logDir/tigger.rep
		echo "[`date`][$SID] Found changes with file(s) from $tiggerDir, start compiling!"
		checkRun "cd $tiggerDir"
		fileList=(`ls`)
		if [ "`echo ${changeFlag[*]} | grep tar`x" != x -o ${#fileList[*]} = 1 ]
		then uncompressFlag=1
		else uncompressFlag=0
		fi
		if [ -f ./$stuID.tar -a $uncompressFlag = 1 ]
		then 
			echo -e "cd $tiggerDir\ntar -xf ./$stuID.tar" | su - $userName
			errCode=$?
			if [ $errCode != 0 ]
			then
				mailFormat=UNCOMPRESS_ERROR
				echo "Error: Error(s) occurred while uncompressing your tar file!" >> $logDir/tigger.rep
				echo "[`date`][$SID] Error(s) occurred while uncompressing for student[$stuID]!"
				return
			fi
			if [ -d ./$stuID ]
			then echo -e "cd $tiggerDir\ncp -r ./$stuID/* ./" | su - $userName
			fi
		fi
		
		$installPath/scripts/secure_mode -start
		if [ -f ./makefile -o -f ./Makefile ]
		then echo -e "cd $tiggerDir\nmake" | timeout $timeOut su - $userName > $tempDir/compile_tigger.log 2>&1 
		elif [ -f ./compile ]
		then 
			chmod +x ./compile
			sed -i 's///g' ./compile
			echo -e "cd $tiggerDir\nbash ./compile" | timeout $timeOut su - $userName > $tempDir/compile_tigger.log 2>&1
		else 
			mailFormat=NO_COMPILE_METHOD
			echo "Error: Cann't find an appropriate method to compile your source file!" >> $logDir/tigger.rep
			echo "[`date`][$SID] No method found to compile source file while testing student[$stuID]!"
			$installPath/scripts/secure_mode -stop
			return
		fi
		errCode=$?
		if [ $errCode = 124 ]
		then 
			mailFormat=COMPILE_TIMEOUT
			echo "Error: Timelimit exceeded while compiling your source file!" >> $logDir/tigger.rep
			echo "[`date`][$SID] Timeout while compiling for student[$stuID]"
			$installPath/scripts/secure_mode -stop
			checkRun cp $tempDir/compile_tigger.log ./
			return
		elif [ $errCode != 0 ]
		then 
			mailFormat=COMPILE_ERROR
			echo "Error: We have encountered with some problems compiling your source files! You may find more details below or in the file attached with this email!" >> $logDir/tigger.rep
			echo "[`date`][$SID] Error(s) occurred while compiling for student[$stuID]"
			$installPath/scripts/secure_mode -stop
			checkRun cp $tempDir/compile_tigger.log ./
			return
		fi
		checkRun cp $tempDir/compile_tigger.log ./

		# Start test
		if [ ! -f ./tiggerC ] && [ ! -f ./tigger -o ! -f ./eeyore ]
		then 
			mailFormat=NO_BINARY_FILE
			echo "Error: Can not locate all the binary files \"tigger, eeyore\" or \"tiggerC\" needed for compilation!" >> $logDir/tigger.rep
			echo "[`date`][$SID] Cannot locate binary file compiled with compiling method for student[$stuID]"
			$installPath/scripts/secure_mode -stop
			return
		fi
			
		for file in $testDir/*.c
		do
			testName=(`basename $file | sed 's/\./ /g'`)
			checkRun cp $file $ftpTemp/test_$SID.c
			if [ -f $tempDir/compile_tigger_*.log ]
			then checkRun rm $tempDir/compile_tigger_*.log
			fi		
			
			if [ -f ./tiggerC ]
			then
				# Use tiggerC compile C file
				echo -e "cd $tiggerDir\n./tiggerC < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.t 2> $tempDir/compile_tigger_c2t.log
				errCode=$?
				if [ $errCode = 124 ]
				then 
					mailFormat=RUN_TIMEOUT
					echo "Error: Timelimit exceeded while compile MiniC file \"${testName}.c\" to tigger with your executable file!" >> $logDir/tigger.rep
					echo "[`date`][$SID] Timelimit exceeded while running tiggerC for \"${testName}.c\" with student[$stuID]'s tiggerC"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_c2t.log ./
					return
				elif [ $errCode != 0 ]
				then
					mailFormat=RUNTIME_ERROR
					echo "Error: Runtime error occurred while compiling MiniC file \"${testName}.c\" to tigger with your excutable file! You may find more details below or in the file attached with this email." >> $logDir/tigger.rep
					echo "[`date`][$SID] Runtime error occurred while running tiggerC for \"${testName}.c\" with student[$stuID]'s tiggerC"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_c2t.log ./
					return
				fi
				checkRun cp $tempDir/compile_tigger_c2t.log ./
			else
				# Use eeyore compile C file
				echo -e "cd $tiggerDir\n./eeyore < $ftpTemp/test_$SID.c" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.e 2> $tempDir/compile_tigger_c2e.log
				errCode=$?
				if [ $errCode = 124 ]
				then 
					mailFormat=RUN_TIMEOUT
					echo "Error: Timelimit exceeded while compile MiniC file \"${testName}.c\" to eeyore with your executable file!" >> $logDir/tigger.rep
					echo "[`date`][$SID] Timelimit exceeded while running eeyore for \"${testName}.c\" with student[$stuID]'s eeyore"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_c2e.log ./
					return
				elif [ $errCode != 0 ]
				then
					mailFormat=RUNTIME_ERROR
					echo "Error: Runtime error occurred while compiling MiniC file \"${testName}.c\" to eeyore with your excutable file! You may find more details below or in the file attached with this email." >> $logDir/tigger.rep
					echo "[`date`][$SID] Runtime error occurred while running eeyore for \"${testName}.c\" with student[$stuID]'s eeyore"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_c2e.log ./
					return
				fi
				checkRun cp $tempDir/compile_tigger_c2e.log ./
			
				# Use tigger compile eeyore file
				echo -e "cd $tiggerDir\n./tigger < $ftpTemp/test_$SID.e" | timeout $timeOut su - $userName  > $ftpTemp/test_$SID.t 2> $tempDir/compile_tigger_e2t.log
				errCode=$?
				if [ $errCode = 124 ]
				then 
					mailFormat=RUN_TIMEOUT
					echo "Error: Timelimit exceeded while compile eeyore file \"${testName}.e\" to tigger with your executable file!" >> $logDir/tigger.rep
					echo "[`date`][$SID] Timelimit exceeded while running tigger for \"${testName}.e\" with student[$stuID]'s tigger"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_e2t.log ./
					return
				elif [ $errCode != 0 ]
				then
					mailFormat=RUNTIME_ERROR
					echo "Error: Runtime error occurred while compiling eeyore file \"${testName}.e\" to tigger with your excutable file! You may find more details below or in the file attached with this email." >> $logDir/tigger.rep
					echo "[`date`][$SID] Runtime error occurred while running tigger for \"${testName}.e\" with student[$stuID]'s tigger"
					$installPath/scripts/secure_mode -stop
					checkRun cp $tempDir/compile_tigger_e2t.log ./
					return
				fi
				checkRun cp $tempDir/compile_tigger_e2t.log ./
			fi
			$installPath/scripts/secure_mode -stop
			
			# Simulating tigger file
			if [ -f $testDir/$testName.input ]
			then timeout $timeOut sudo $installPath/bin/Tigger $ftpTemp/test_$SID.t < $testDir/$testName.input > $tempDir/${testName}_$SID.result 2> $tempDir/simulate_tigger.log
			else timeout $timeOut sudo $installPath/bin/Tigger $ftpTemp/test_$SID.t > $tempDir/${testName}_$SID.result 2> $tempDir/simulate_tigger.log
			fi
			errCode=$?
			if [ $errCode = 124 ]
			then
				mailFormat=SIM_TIMEOUT
				echo "Error: Timelimit exceeded while simulating \"${testName}.c\" with the tigger code generated!" >> $logDir/tigger.rep
				echo "[`date`][$SID] Timelimit exceeded while simulating \"${testName}.c\" for student[$stuID]"
				checkRun cp $tempDir/simulate_tigger.log ./
				return
			fi
			if [ "`grep "Error\|error\|fault" $tempDir/${testName}_$SID.result`x" != x -o -s $tempDir/simulate_tigger.log ]
			then
				mailFormat=SIM_ERROR
				echo "Error: Runtime occurred while simulating \"${testName}.c\" with the eeyore code generated!" >> $logDir/tigger.rep
				echo "[`date`][$SID] Runtime error occurred while simulating \"${testName}.c\" for student[$stuID]"
				cat $tempDir/${testName}_$SID.result >> $tempDir/simulate_tigger.log
				checkRun cp $tempDir/simulate_tigger.log ./
				return
			fi
			echo $errCode >> $tempDir/${testName}_$SID.result
			checkRun cp $tempDir/simulate_tigger.log ./
			
			# Comparing simulation result
			diffInfo=`diff $tempDir/${testName}_$SID.result $testDir/$testName.output`
			if [ "${diffInfo}x" != x ]
			then 
				mailFormat=SIM_WRONG_RESULT
				echo "Error: Simulation result mismatch with \"${testName}.output\"" >> $logDir/tigger.rep
				echo "[`date`][$SID] Simulation result mismatch for student[$stuID] with \"${testName}.output\""
				return
			fi
		done
		echo "Congratulations! You have passed the test for lab-tigger!" >> $logDir/tigger.rep
		mailFormat=TEST_PASS
	else mailFormat=0
	fi
}

if [ ! -d $installPath ]
then 
	echo "<Error> Minic Checker root directory not found!"
	exit
fi

while [ 1 ]
do
	echo "[`date`][$SID] Start checking homeworks"
	stuList=`checkRun "cat $installPath/config/students.list"`
	for stuID in $stuList
	do
		checkLab
		if [ $mailFormat != 0 ]
		then 
			echo -e "\n  This report was automatically generated by Minic Checker at [`date`]">> $logDir/tigger.rep
			echo "[`date`][$SID] Check finished. Get status [$mailFormat] for student [$stuID]! Sending email..."
			$installPath/scripts/send_mail $stuID@pku.edu.cn -f $installPath/config/minic_checker.mf -t CHECK TIGGER $mailFormat
		fi
	done
	sleep $interval
done
